SEQUENCE: 023_badminton
INVALID_ARIAS: []
INVALID_EXOS: []
CALIBRATION:
  MANUAL_EXO_CAMERAS:
  - cam04
  - cam05
BBOX:
  VIS_CAMERAS:
  - cam02
  - cam04
  - cam05
  - aria01
  MIN_VERTICES: 40
  EGO:
    MIN_AREA_RATIO: 0.001
    CLOSE_BBOX_DISTANCE: 2.0
    CLOSE_BBOX_MIN_AREA_RATIO: 0.01
    MAX_ASPECT_RATIO: 4
    MIN_ASPECT_RATIO: 0.4
  EXO:
    MIN_AREA_RATIO: 0.0001
    MAX_ASPECT_RATIO: 5
    MIN_ASPECT_RATIO: 0.1
POSE2D:
  VIS_CAMERAS:
  - cam02
  - cam04
  - cam05
  - aria01
  DEBUG: false
  USE_BBOX_DETECTOR: true
  DETECTOR_CONFIG_FILE: ./external/mmpose/demo/mmdetection_cfg/faster_rcnn_x101_64x4d_fpn_mstrain_3x_coco.py
  DETECTOR_CHECKPOINT: https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_x101_64x4d_fpn_mstrain_3x_coco/faster_rcnn_x101_64x4d_fpn_mstrain_3x_coco_20210524_124528-26c63de6.pth
  DETECTOR_MIN_IOU: 0.1
  RGB_CONFIG_FILE: ./external/mmpose/configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hrnet_w48_coco_384x288_udp.py
  RGB_CHECKPOINT: https://download.openmmlab.com/mmpose/top_down/udp/hrnet_w48_coco_384x288_udp-0f89c63e_20210223.pth
  RGB_THRES: 0.2
  RGB_VIS_THRES: 0.2
  GRAY_CONFIG_FILE: ./external/mmpose/configs/wholebody/2d_kpt_sview_rgb_img/topdown_heatmap/coco-wholebody-grayscale/hrnet_w48_coco_wholebody_384x288_dark_plus.py
  GRAY_CHECKPOINT: https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w48_coco_wholebody_384x288_dark-f5726563_20200918.pth
  GRAY_THRES: 0.5
  GRAY_VIS_THRES: 0.5
  MIN_VIS_KEYPOINTS: 5
  OVERLAP_OKS_THRES: 0.7
  BBOX_THRES: 0.5
  VIS:
    RADIUS:
      EXO_RGB: 10
      EGO_RGB: 5
      EGO_LEFT: 2
      EGO_RIGHT: 2
    THICKNESS:
      EXO_RGB: 10
      EGO_RGB: 5
      EGO_LEFT: 2
      EGO_RIGHT: 2
POSE3D:
  VIS_CAMERAS:
  - cam02
  - cam04
  - cam05
  - aria01
  KEYPOINTS_THRES: 0.5
  BBOX_AREA_THRES: 0.002
  NUM_ITERS: 1000
  REPROJECTION_ERROR_EPSILON: 0.01
  MIN_VIEWS: 2
  SECONDARY_MIN_VIEWS: 3
  INCLUDE_CONFIDENCE: true
REFINE_POSE3D:
  DEBUG: true
  STD_THRES: 10
  WINDOW_LENGTH: 10
  MOTION_THRES: 300
FIT_POSE3D:
  VIS_CAMERAS:
  - cam02
  - cam04
  - cam05
  - aria01
  DEBUG: true
  NUM_EPOCHS: 10
  NUM_ITERS: 500
  LR: 0.1
  MAX_ITER: 20
  INIT_POSE_LOSS_WEIGHT: 1
  SYMMETRY_LOSS_WEIGHT: 1
  TEMPORAL_LOSS_WEIGHT: 1
  LIMB_LENGTH_LOSS_WEIGHT: 1
  FTOL: 1e-4
  GLOBAL_ITERS: 3
INIT_SMPL:
  VIS: false
  VIS_CAMERAS:
  - cam05
SMPL:
  VIS_CAMERAS:
  - cam02
  - cam04
  - cam05
  - aria01
  DEBUG: false
  VERBOSE: true
  CONFIG_FILE: smplify3d_temporal.py
  ARIA_NAME_LIST:
  - aria01
  - aria02
  - aria03
  - aria04
  ARIA_GENDER_LIST:
  - neutral
  - neutral
  - neutral
  - neutral
  NUM_EPOCHS_LIST:
  - 10
  - 10
  - 10
  - 10
  STAGE1_ITERS_LIST:
  - 50
  - 50
  - 50
  - 50
  STAGE2_ITERS_LIST:
  - 20
  - 20
  - 20
  - 20
  STAGE3_ITERS_LIST:
  - 120
  - 120
  - 120
  - 120
BLENDER:
  SCENE_FILE: badminton/badminton.blend
  COLORS: blue###green###red###yellow
  MAX_OFFSET: 0.25
  TOLERANCE: 1e-5
  OVERLAY: true
  OVERLAY_CAMERA: cam12
